2023-09-16 09:42:47,143 INFO    StreamThr :884 [internal.py:wandb_internal():86] W&B internal server running at pid: 884, started at: 2023-09-16 09:42:47.142891
2023-09-16 09:42:47,144 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: status
2023-09-16 09:42:47,147 INFO    WriterThread:884 [datastore.py:open_for_write():85] open: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\run-l1dcri0a.wandb
2023-09-16 09:42:47,148 DEBUG   SenderThread:884 [sender.py:send():379] send: header
2023-09-16 09:42:47,184 DEBUG   SenderThread:884 [sender.py:send():379] send: run
2023-09-16 09:42:47,680 INFO    SenderThread:884 [dir_watcher.py:__init__():211] watching files in: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files
2023-09-16 09:42:47,680 INFO    SenderThread:884 [sender.py:_start_run_threads():1121] run started: l1dcri0a with start time 1694850167.143891
2023-09-16 09:42:47,692 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: check_version
2023-09-16 09:42:47,693 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: check_version
2023-09-16 09:42:47,916 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: run_start
2023-09-16 09:42:47,928 DEBUG   HandlerThread:884 [system_info.py:__init__():32] System info init
2023-09-16 09:42:47,929 DEBUG   HandlerThread:884 [system_info.py:__init__():47] System info init done
2023-09-16 09:42:47,929 INFO    HandlerThread:884 [system_monitor.py:start():181] Starting system monitor
2023-09-16 09:42:47,929 INFO    SystemMonitor:884 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-16 09:42:47,929 INFO    HandlerThread:884 [system_monitor.py:probe():201] Collecting system info
2023-09-16 09:42:47,934 INFO    SystemMonitor:884 [interfaces.py:start():190] Started cpu monitoring
2023-09-16 09:42:47,934 INFO    SystemMonitor:884 [interfaces.py:start():190] Started disk monitoring
2023-09-16 09:42:47,935 INFO    SystemMonitor:884 [interfaces.py:start():190] Started gpu monitoring
2023-09-16 09:42:47,935 INFO    SystemMonitor:884 [interfaces.py:start():190] Started memory monitoring
2023-09-16 09:42:47,944 INFO    SystemMonitor:884 [interfaces.py:start():190] Started network monitoring
2023-09-16 09:42:47,972 DEBUG   HandlerThread:884 [system_info.py:probe():196] Probing system
2023-09-16 09:42:47,973 DEBUG   HandlerThread:884 [system_info.py:_probe_git():181] Probing git
2023-09-16 09:42:47,985 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:47,985 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:47,986 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:47,986 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:48,067 DEBUG   HandlerThread:884 [system_info.py:_probe_git():189] Probing git done
2023-09-16 09:42:48,067 DEBUG   HandlerThread:884 [system_info.py:probe():244] Probing system done
2023-09-16 09:42:48,067 DEBUG   HandlerThread:884 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.11.3', 'heartbeatAt': '2023-09-16T07:42:47.972619', 'startedAt': '2023-09-16T07:42:47.133889', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'c:\\Users\\calle\\Documents\\GitHub\\robust-rl\\cliff_car\\cliff_car_experiments.py', 'codePathLocal': 'cliff_car_experiments.py', 'codePath': 'cliff_car\\cliff_car_experiments.py', 'git': {'remote': 'https://github.com/TheGoldenChicken/robust-rl.git', 'commit': 'aae28907e2dbfe0cf4343d356df23ccab31b1e04'}, 'email': 'calle@rygecarlsen.dk', 'root': 'C:/Users/calle/Documents/GitHub/robust-rl', 'host': 'DESKTOP-OKSREAS', 'username': 'calle', 'executable': 'C:\\Users\\calle\\Anaconda3\\envs\\bachelor\\python.exe', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3801.0, 'min': 0.0, 'max': 3801.0}, 'cpu_freq_per_core': [{'current': 3801.0, 'min': 0.0, 'max': 3801.0}], 'disk': {'/': {'total': 931.3984336853027, 'used': 343.2195281982422}}, 'gpu': 'GeForce GTX 660', 'gpu_count': 2, 'gpu_devices': [{'name': 'GeForce GTX 660', 'memory_total': 3221225472}, {'name': 'GeForce GTX 660', 'memory_total': 3221225472}], 'memory': {'total': 31.91257095336914}}
2023-09-16 09:42:48,068 INFO    HandlerThread:884 [system_monitor.py:probe():211] Finished collecting system info
2023-09-16 09:42:48,068 INFO    HandlerThread:884 [system_monitor.py:probe():214] Publishing system info
2023-09-16 09:42:48,068 DEBUG   HandlerThread:884 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-09-16 09:42:48,069 DEBUG   HandlerThread:884 [system_info.py:_save_pip():68] Saving pip packages done
2023-09-16 09:42:48,069 DEBUG   HandlerThread:884 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-09-16 09:42:48,072 ERROR   HandlerThread:884 [system_info.py:_save_conda():86] Error saving conda packages: [WinError 2] Den angivne fil blev ikke fundet
Traceback (most recent call last):
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    subprocess.call(
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Den angivne fil blev ikke fundet
2023-09-16 09:42:48,076 DEBUG   HandlerThread:884 [system_info.py:_save_conda():87] Saving conda packages done
2023-09-16 09:42:48,077 INFO    HandlerThread:884 [system_monitor.py:probe():216] Finished publishing system info
2023-09-16 09:42:48,086 DEBUG   SenderThread:884 [sender.py:send():379] send: files
2023-09-16 09:42:48,086 INFO    SenderThread:884 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-09-16 09:42:48,098 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: stop_status
2023-09-16 09:42:48,098 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: stop_status
2023-09-16 09:42:48,103 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: internal_messages
2023-09-16 09:42:48,683 INFO    Thread-16 :884 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\conda-environment.yaml
2023-09-16 09:42:48,683 INFO    Thread-16 :884 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\wandb-metadata.json
2023-09-16 09:42:48,683 INFO    Thread-16 :884 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\requirements.txt
2023-09-16 09:42:49,117 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-16 09:42:50,013 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:50,013 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:50,013 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:50,013 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:52,040 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:52,040 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:52,041 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:52,041 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:54,067 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:54,067 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:54,068 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:54,068 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:54,145 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:42:56,095 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:56,095 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:56,095 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:56,096 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:58,113 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:58,113 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:58,113 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:58,114 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:42:59,187 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:00,143 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:00,143 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:00,143 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:00,143 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:01,413 INFO    wandb-upload_0:884 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000012D7069AB50>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D7069AB50>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calle\Anaconda3\envs\bachelor\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D7069AB50>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)"))
2023-09-16 09:43:02,172 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:02,172 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:02,173 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:02,173 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:04,192 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:04,192 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:04,193 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:04,193 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:04,223 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:06,222 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:06,223 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:06,223 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:06,223 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:08,254 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:08,254 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:08,255 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:08,255 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:09,256 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:10,278 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:10,278 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:10,278 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:10,279 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:12,306 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:12,306 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:12,307 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:12,307 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:14,286 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:14,331 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:14,332 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:14,332 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:14,332 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:16,364 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:16,364 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:16,364 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:16,364 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:17,831 WARNING FileStreamThread:884 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D70BBE850>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000012D3FECF310>>, timeout=180), args: ('https://api.wandb.ai/files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 09:43:18,384 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:43:18,390 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:43:18,396 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:43:18,396 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-09-16 09:43:18,412 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:18,412 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:18,413 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:18,413 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:19,324 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:20,193 WARNING FileStreamThread:884 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D70BBD550>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000012D3FECF310>>, timeout=180), args: ('https://api.wandb.ai/files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 09:43:20,439 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:20,439 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:20,440 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:20,440 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:22,458 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:22,458 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:22,459 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:22,459 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:24,369 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:24,431 WARNING FileStreamThread:884 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D7069B090>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000012D3FECF310>>, timeout=180), args: ('https://api.wandb.ai/files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 09:43:24,476 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:24,477 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:24,477 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:24,477 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:26,493 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:26,493 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:26,494 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:26,494 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:28,522 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:28,522 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:28,522 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:28,522 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:29,401 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:30,549 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:30,550 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:30,550 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:30,550 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:32,565 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:32,566 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:32,566 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:32,566 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:33,155 WARNING FileStreamThread:884 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D70632590>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000012D3FECF310>>, timeout=180), args: ('https://api.wandb.ai/files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 09:43:34,444 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:34,586 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:34,586 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:34,587 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:34,587 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:36,601 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:36,601 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:36,602 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:36,602 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:38,627 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:38,627 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:38,628 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:38,628 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:39,494 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:40,642 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:40,642 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:40,643 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:40,643 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:42,673 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:42,673 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:42,673 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:42,673 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:44,530 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:44,688 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:44,688 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:44,689 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:44,689 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:46,714 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:46,714 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:46,715 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:46,715 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:47,946 DEBUG   SystemMonitor:884 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-16 09:43:48,724 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:43:48,731 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:43:48,736 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:43:48,737 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-09-16 09:43:48,751 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:48,751 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:48,752 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:48,752 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:49,566 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:50,776 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:50,777 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:50,777 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:50,777 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:52,805 WARNING FileStreamThread:884 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012D706FC610>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000012D3FECF310>>, timeout=180), args: ('https://api.wandb.ai/files/fagprojekt/robust-rl-cliff-car/l1dcri0a/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 09:43:52,806 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:52,806 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:52,806 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:52,806 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:54,596 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:43:54,834 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:54,834 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:54,835 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:54,835 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:56,860 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:56,860 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:56,861 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:56,861 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:58,878 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:58,878 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:58,879 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:58,879 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:43:59,635 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:00,906 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:00,906 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:00,907 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:00,907 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:02,928 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:02,928 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:02,929 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:02,929 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:04,673 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:04,954 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:04,955 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:04,955 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:04,955 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:06,983 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:06,984 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:06,984 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:06,984 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:09,009 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:09,009 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:09,010 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:09,010 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:09,704 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:11,040 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:11,040 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:11,041 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:11,041 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:13,058 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:13,059 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:13,059 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:13,059 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:14,754 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:15,084 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:15,084 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:15,084 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:15,085 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:17,113 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:17,114 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:17,114 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:17,114 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:19,121 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:44:19,127 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:44:19,133 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:44:19,133 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-09-16 09:44:19,148 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:19,148 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:19,148 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:19,148 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:19,791 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:21,165 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:21,165 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:21,166 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:21,166 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:23,195 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:23,195 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:23,196 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:23,196 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:24,822 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:25,216 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:25,216 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:25,217 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:25,217 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:26,597 INFO    wandb-upload_0:884 [upload_job.py:push():131] Uploaded file C:\Users\calle\AppData\Local\Temp\tmpujhip4u0wandb\lfzn9sog-wandb-metadata.json
2023-09-16 09:44:27,239 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:27,239 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:27,239 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:27,239 ERROR   gpu       :884 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-16 09:44:28,286 DEBUG   SenderThread:884 [sender.py:send():379] send: telemetry
2023-09-16 09:44:28,286 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: status_report
2023-09-16 09:44:28,288 DEBUG   SenderThread:884 [sender.py:send():379] send: exit
2023-09-16 09:44:28,288 INFO    SenderThread:884 [sender.py:send_exit():584] handling exit code: 1
2023-09-16 09:44:28,288 INFO    SenderThread:884 [sender.py:send_exit():586] handling runtime: 0
2023-09-16 09:44:28,288 INFO    SenderThread:884 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-16 09:44:28,289 INFO    SenderThread:884 [sender.py:send_exit():592] send defer
2023-09-16 09:44:28,289 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: poll_exit
2023-09-16 09:44:28,289 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,289 DEBUG   SenderThread:884 [sender.py:send():379] send: stats
2023-09-16 09:44:28,289 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-16 09:44:28,289 DEBUG   SenderThread:884 [sender.py:send():379] send: stats
2023-09-16 09:44:28,290 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,290 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 0
2023-09-16 09:44:28,290 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 1
2023-09-16 09:44:28,290 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,290 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-16 09:44:28,290 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,290 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 1
2023-09-16 09:44:28,290 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 2
2023-09-16 09:44:28,290 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,291 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-16 09:44:28,291 INFO    HandlerThread:884 [system_monitor.py:finish():190] Stopping system monitor
2023-09-16 09:44:28,291 DEBUG   SystemMonitor:884 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-16 09:44:28,291 DEBUG   SystemMonitor:884 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-16 09:44:28,291 INFO    HandlerThread:884 [interfaces.py:finish():202] Joined cpu monitor
2023-09-16 09:44:28,298 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:44:28,298 INFO    HandlerThread:884 [interfaces.py:finish():202] Joined disk monitor
2023-09-16 09:44:28,304 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:44:28,311 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: Not Supported
2023-09-16 09:44:28,311 ERROR   gpu       :884 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-09-16 09:44:28,311 INFO    HandlerThread:884 [interfaces.py:finish():202] Joined gpu monitor
2023-09-16 09:44:28,311 INFO    HandlerThread:884 [interfaces.py:finish():202] Joined memory monitor
2023-09-16 09:44:28,311 INFO    HandlerThread:884 [interfaces.py:finish():202] Joined network monitor
2023-09-16 09:44:28,311 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,311 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 2
2023-09-16 09:44:28,311 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 3
2023-09-16 09:44:28,312 DEBUG   SenderThread:884 [sender.py:send():379] send: stats
2023-09-16 09:44:28,312 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,312 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-16 09:44:28,312 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,312 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 3
2023-09-16 09:44:28,312 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 4
2023-09-16 09:44:28,312 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,312 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-16 09:44:28,312 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,312 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 4
2023-09-16 09:44:28,313 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 5
2023-09-16 09:44:28,313 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,313 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-16 09:44:28,313 DEBUG   SenderThread:884 [sender.py:send():379] send: summary
2023-09-16 09:44:28,313 INFO    SenderThread:884 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-16 09:44:28,314 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,314 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 5
2023-09-16 09:44:28,314 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 6
2023-09-16 09:44:28,314 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,314 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-16 09:44:28,314 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,314 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 6
2023-09-16 09:44:28,317 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: status_report
2023-09-16 09:44:28,473 INFO    Thread-16 :884 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\output.log
2023-09-16 09:44:28,474 INFO    Thread-16 :884 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\wandb-summary.json
2023-09-16 09:44:28,524 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 7
2023-09-16 09:44:28,524 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:28,525 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-16 09:44:28,525 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:28,525 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 7
2023-09-16 09:44:29,487 INFO    Thread-16 :884 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\config.yaml
2023-09-16 09:44:29,867 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:30,292 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 8
2023-09-16 09:44:30,292 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:30,292 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-16 09:44:30,292 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:30,292 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 8
2023-09-16 09:44:30,292 INFO    SenderThread:884 [job_builder.py:build():281] Attempting to build job artifact
2023-09-16 09:44:30,293 INFO    SenderThread:884 [job_builder.py:_get_source_type():393] is repo sourced job
2023-09-16 09:44:30,299 INFO    SenderThread:884 [job_builder.py:build():369] adding wandb-job metadata file
2023-09-16 09:44:30,309 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 9
2023-09-16 09:44:30,309 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:30,309 DEBUG   SenderThread:884 [sender.py:send():379] send: artifact
2023-09-16 09:44:30,309 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-16 09:44:30,496 INFO    Thread-16 :884 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\output.log
2023-09-16 09:44:31,589 INFO    wandb-upload_0:884 [upload_job.py:push():86] Skipped uploading C:\Users\calle\AppData\Local\wandb\wandb\artifacts\staging\tmpzseh47ic
2023-09-16 09:44:31,942 INFO    wandb-upload_1:884 [upload_job.py:push():89] Uploaded file C:\Users\calle\AppData\Local\wandb\wandb\artifacts\staging\tmpsc66el08
2023-09-16 09:44:33,317 INFO    SenderThread:884 [sender.py:send_artifact():1453] sent artifact job-https___github.com_TheGoldenChicken_robust-rl.git_cliff_car_cliff_car_experiments.py - {'id': 'QXJ0aWZhY3Q6NTcwNzA4MzM5', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjk3Nzg2Njc2', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6NTcwNjU4MjU2', 'versionIndex': 8}}}
2023-09-16 09:44:33,317 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:33,318 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: status_report
2023-09-16 09:44:33,318 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 9
2023-09-16 09:44:33,318 INFO    SenderThread:884 [dir_watcher.py:finish():358] shutting down directory watcher
2023-09-16 09:44:33,517 INFO    SenderThread:884 [dir_watcher.py:finish():388] scan: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files
2023-09-16 09:44:33,518 INFO    SenderThread:884 [dir_watcher.py:finish():402] scan save: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\conda-environment.yaml conda-environment.yaml
2023-09-16 09:44:33,518 INFO    SenderThread:884 [dir_watcher.py:finish():402] scan save: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\config.yaml config.yaml
2023-09-16 09:44:33,518 INFO    SenderThread:884 [dir_watcher.py:finish():402] scan save: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\output.log output.log
2023-09-16 09:44:33,520 INFO    SenderThread:884 [dir_watcher.py:finish():402] scan save: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\requirements.txt requirements.txt
2023-09-16 09:44:33,520 INFO    SenderThread:884 [dir_watcher.py:finish():402] scan save: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\wandb-metadata.json wandb-metadata.json
2023-09-16 09:44:33,521 INFO    SenderThread:884 [dir_watcher.py:finish():402] scan save: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\wandb-summary.json wandb-summary.json
2023-09-16 09:44:33,523 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 10
2023-09-16 09:44:33,523 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:33,524 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 10
2023-09-16 09:44:33,525 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:33,525 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 10
2023-09-16 09:44:33,525 INFO    SenderThread:884 [file_pusher.py:finish():175] shutting down file pusher
2023-09-16 09:44:33,969 INFO    wandb-upload_0:884 [upload_job.py:push():131] Uploaded file c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\config.yaml
2023-09-16 09:44:34,120 INFO    wandb-upload_1:884 [upload_job.py:push():131] Uploaded file c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\output.log
2023-09-16 09:44:34,143 INFO    wandb-upload_2:884 [upload_job.py:push():131] Uploaded file c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\requirements.txt
2023-09-16 09:44:34,181 INFO    wandb-upload_3:884 [upload_job.py:push():131] Uploaded file c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\files\wandb-summary.json
2023-09-16 09:44:34,387 INFO    Thread-15 (_thread_body):884 [sender.py:transition_state():612] send defer: 11
2023-09-16 09:44:34,387 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:34,387 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 11
2023-09-16 09:44:34,387 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:34,387 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 11
2023-09-16 09:44:34,387 INFO    SenderThread:884 [file_pusher.py:join():181] waiting for file pusher
2023-09-16 09:44:34,388 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 12
2023-09-16 09:44:34,388 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:34,388 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 12
2023-09-16 09:44:34,388 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:34,388 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 12
2023-09-16 09:44:34,388 INFO    SenderThread:884 [file_stream.py:finish():594] file stream finish called
2023-09-16 09:44:34,910 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 09:44:35,001 INFO    SenderThread:884 [file_stream.py:finish():598] file stream finish is done
2023-09-16 09:44:35,001 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 13
2023-09-16 09:44:35,001 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:35,001 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 13
2023-09-16 09:44:35,001 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:35,001 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 13
2023-09-16 09:44:35,002 INFO    SenderThread:884 [sender.py:transition_state():612] send defer: 14
2023-09-16 09:44:35,002 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: defer
2023-09-16 09:44:35,002 DEBUG   SenderThread:884 [sender.py:send():379] send: final
2023-09-16 09:44:35,002 INFO    HandlerThread:884 [handler.py:handle_request_defer():170] handle defer: 14
2023-09-16 09:44:35,002 DEBUG   SenderThread:884 [sender.py:send():379] send: footer
2023-09-16 09:44:35,002 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: defer
2023-09-16 09:44:35,002 INFO    SenderThread:884 [sender.py:send_request_defer():608] handle sender defer: 14
2023-09-16 09:44:35,003 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-16 09:44:35,003 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: server_info
2023-09-16 09:44:35,003 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: get_summary
2023-09-16 09:44:35,003 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: poll_exit
2023-09-16 09:44:35,003 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: sampled_history
2023-09-16 09:44:35,004 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: server_info
2023-09-16 09:44:35,004 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: internal_messages
2023-09-16 09:44:35,005 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: job_info
2023-09-16 09:44:35,180 DEBUG   SenderThread:884 [sender.py:send_request():406] send_request: job_info
2023-09-16 09:44:35,181 INFO    MainThread:884 [wandb_run.py:_footer_history_summary_info():3557] rendering history
2023-09-16 09:44:35,181 INFO    MainThread:884 [wandb_run.py:_footer_history_summary_info():3589] rendering summary
2023-09-16 09:44:35,181 INFO    MainThread:884 [wandb_run.py:_footer_sync_info():3516] logging synced files
2023-09-16 09:44:35,182 DEBUG   HandlerThread:884 [handler.py:handle_request():144] handle_request: shutdown
2023-09-16 09:44:35,182 INFO    HandlerThread:884 [handler.py:finish():840] shutting down handler
2023-09-16 09:44:36,014 INFO    WriterThread:884 [datastore.py:close():294] close: c:\Users\calle\Documents\GitHub\robust-rl\cliff_car\wandb\run-20230916_094247-l1dcri0a\run-l1dcri0a.wandb
2023-09-16 09:44:36,188 INFO    SenderThread:884 [sender.py:finish():1531] shutting down sender
2023-09-16 09:44:36,188 INFO    SenderThread:884 [file_pusher.py:finish():175] shutting down file pusher
2023-09-16 09:44:36,188 INFO    SenderThread:884 [file_pusher.py:join():181] waiting for file pusher
